server:
  port: 8085

spring:
  profile:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tsherpa
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  messages:
    basename: messages
    encoding: UTF-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tsherpa.team35.entity
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework: info

itemImgLocation: C:/team35/item
uploadPath: file:///C:/team35